namespace IRMSGen.Contracts.Project;

public sealed class ProjectDefinition
{
    public string Category { get; set; } = "Inquiry";

    public string ServiceName { get; set; } = "OrderService";

    public string RootNamespace { get; set; } = "Company.Services.OrderService";

    public string TargetFramework { get; set; } = "net8.0";

    public string Description { get; set; } = "Generated by IRMSGen.";

    public static ProjectDefinition CreateDefault() => new();
}
